awesome-jellyfin/awesome-jellyfin

README.md
Hi,
this PR adds the [xsrv.jellyfin](https://github.com/nodiscc/xsrv/tree/master/roles/jellyfin) ansible role, which can be used to deploy Jellyfin on any Debian-based Linux machine.
The role can be used from the [xsrv](https://xsrv.readthedocs.io/en/latest/) command-line tool/ansible wrapper, or with ansible [command-line](https://docs.ansible.com/ansible/latest/user_guide/command_line_tools.html) tools. Optionally it integrates with [netdata](https://github.com/nodiscc/xsrv/tree/master/roles/monitoring_netdata) for instance health monitoring, [apache](https://github.com/nodiscc/xsrv/tree/master/roles/apache) for reverse proxy and SSL/TLS certificate management, [rsnapshot](https://github.com/nodiscc/xsrv/tree/master/roles/backup) for automatic backups, and …
=> other: add nodiscc.xsrv.jellyfin ansible role

README.md
The Locatarr repository got moved into its own organization and this PR updates the URL to reflect that change.
=> fix: Update Locatarr URL

THEMES.md
On the github page it said: `This skin's development has been halted for sometime` so I think it's best to remove it for now.
**Project Link**
https://github.com/prayag17/JellyFlix
=> Removed JellyFlix Theme

README.md
I don't see the tag used anywhere in the readme file, so I don't think the tag is used anymore.
=> Remove the "Mobile App" Tag 

THEMES.md, assets/clients/clients.yaml
- Fixed IzzySoft Icon missing for Findroid
- Added notice for BlueBerry Theme currently not working duo to [Codeberg DDoS Attacks](https://status.codeberg.eu/status/codeberg)
=> Fix Icon and added notice

README.md
As mentioned in #59 and #60, the original Anilist repo is not maintained for the foreseeable future.
The link was exchanged with a maintained alternative repository that was recommended by the original author.
=> Refactor AnilistSync to maintained alternative

README.md
Jellyfin Media Analyzer asks on its readme to use its fork, so you might as well replace it.
=> Replace jellyfin-plugin-media-analyzer with its updated fork jellyfin-intro-skipper

THEMES.md
It seems the original author has recently deprecated their project https://codeberg.org/Udon/BlueBerry so i've added the key to the themes and added a deprecated notice next to their theme.
I originally had removed this completely but thought that was a bit harsh but if you want me to remove it and just out-right replace it, let me know.
=> Added Jamfin/Deprecated BlueBerry

README.md
Added Cloud Seeder by IPv6.rs to the `other` area. Cloud Seeder lets you 1-click install Jellyfin on Windows, MacOS and Linux!
Thank you for the consideration!
=> docs: Added Cloud Seeder to other area

README.md
A tool to automatically make and update jellyfin collections based on internet lists such as IMDb and letterboxd.
=> Add Jellyfin-Auto-Collections

README.md
Changelog: 
- Merged Duplicate
- Moved TubeArchivist plugin to the metadata subsection.
=> A tidy up of the Plugins section

assets/clients/clients.yaml
Vue is indeed an official client.
A few more things, but out of the scope of this PR and leaving it up to the maintainers of this curated list:
* Not sure if music/reader distinctions are just for clients that are focused in those specific media types or it's applicable if it's supported. In the case of Vue, although it wants to cover all use cases, I mainly use Jellyfin for listening music, so the music playback it's one of the things that I think it does really good. We have [a cool fullscreen player](https://github.com/jellyfin/jellyfin-vue/pull/520) and a [spectogram](https://github.com/jellyfin/jellyfin-vue/pull/2043).
* We also have builds for Windows/MacOS/Linux using Tauri but it's provided in a best-effort basis and we don't ship it "first and foremost". We have them continuosly …
=> refactor: mark vue as official

assets/clients/clients.yaml
Hello,
This PR adds VidHub as a desktop, iOS/iPadOS/TvOS client:
https://okaapps.com/product/1659622164
https://apps.apple.com/us/app/vidhub-video-library-player/id1659622164
It's a direct competitor of Infuse, but works better (and somehow way better in local network) if you'd ask me.
Since I could not see in this list, I humbly tried to add to yaml file so it could populated on the next build.
=> VidHub added as client

README.md
Added information that I previously sent to issues:
[jellyfin-plugin-kinopoisk](https://github.com/LinFor/jellyfin-plugin-kinopoisk) - Metadata provider for [Kinopoisk](https://www.kinopoisk.ru/). https://github.com/awesome-jellyfin/awesome-jellyfin/issues/85
[Jellyfin Plugin Stash](https://github.com/DirtyRacer1337/Jellyfin.Plugin.Stash) - Metadata provider for Metadata provider for [Stash](https://github.com/stashapp/stash). https://github.com/awesome-jellyfin/awesome-jellyfin/issues/87
[Jellyfin Plugin ThePornDB](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB) - Metadata provider for ThePornDB. https://github.com/awesome-jellyfin/awesome-jellyfin/issues/88
[Jellyfin Plugin PhoenixAdult](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult) - Metadata provider …
=> Adding new information

README.md
This Pull Request adds streamystats to the list. Streamystats is a statistics service for Jellyfin, providing analytics and data visualization.
Resolves #119
=> Add streamystats

README.md
Adds **[Explo](https://github.com/Explo)** to the README.
Closes #137
(automatically generated)
=> (auto) Add `Explo` to Awesome Jellyfin

README.md
Adds **[jellyplist](https://github.com/jellyplist)** to the README.
Closes #136
(automatically generated)
=> (auto) Add `jellyplist` to Awesome Jellyfin

README.md
This program is designed to interact with the Jellyfin API, retrieve a list of HDR-supported movies, and automatically download their covers (posters) from The Movie Database (TMDb). The program also adds an HDR logo to the top right corner of all downloaded covers and saves the results in a local folder.
=> Added jellyfin-poster-hrd-logo

README.md
I moved the repo to a own github org https://github.com/intro-skipper/
=> chore: update `intro-skipper` location

assets/clients/clients.yaml
A new Jellyfin music client, which supports Mac/iPad/iPhone: https://monk-studio.com/finer
=> Add Finer into clients

README.md
Add my guide for hosting Jellyfin on macOS. Dives into advanced topics like remote connections, startup automation, monitoring dashboards, and geo-filtering.
=> feat: Add `jellyfin-on-macos` guide
