awesome-jellyfin/awesome-jellyfin

README.md

+ Added 'MediaTracker' to 'Other'

added MediaTracker

---

README.md

feat: added `stale` label

---

README.md

The old [intro skipper](https://github.com/ConfusedPolarBear/intro-skipper) has being archived

Updated Intro Skipper Plugin Link

---

README.md

feat: added `Threadfin`

---

README.md
THEMES.md

Added
+ [Fixarr](https://github.com/sachinsenal0x64/FIXARR)
+ [Movary](https://github.com/leepeuker/movary)
+ [BlueBerry](https://codeberg.org/Udon/BlueBerry) Theme
Fixed
+ Old banner used in Theme.md

Added some apps and a theme

---

assets/clients/clients.yaml

closes https://github.com/awesome-jellyfin/clients/pull/1

fix[clients]: added Finamp iOS

---

assets/clients/clients.yaml

For this Apps
+ JellyPlayer
+ Gelli
+ Jellybook
Also Fixes the [Pull Request #37](https://github.com/awesome-jellyfin/awesome-jellyfin/pull/37)

Fixed Apps showing as proprietary

---

assets/clients/clients.yaml

Added Symfonium under Android Music.

Feat: Added Symfonium Client

---

README.md

**Project Description**
Query your Jellyfin server for the movies, tv episodes, audio tracks, and audiobooks in your libraries. Then delete media items you no longer want taking up disk space.
**Project link**
https://github.com/terrelsa13/MUMC

[REQUEST] Multi-User Media Cleaner

---

README.md

**Project Description**
It manage Jellyfin Media Segment positions.
**Project link**
https://github.com/endrl/segment-editor

[REQUEST] Jellyfin Segment Editor

---

README.md

**Project Description**
Easily add content from YouTube to your Jellyfin installation.
**Project link**
https://github.com/AECX/FinTube

[REQUEST] FinTube 

---

README.md

This PR adds [jellyfin-plugin-enigma2](https://github.com/knackebrot/jellyfin-plugin-enigma2)
resolves #53

feat: enigma2 plugin

---

README.md

<table>
<tr align="center">
<td><img src="https://raw.githubusercontent.com/Tetrax-10/jellyfin-cover-art-generator/main/assets/Movies-dune.jpg" style="width: 400px;"></td>
<td><img src="https://raw.githubusercontent.com/Tetrax-10/jellyfin-cover-art-generator/main/assets/TV Shows-chernobyl.jpg" style="width: 400px;"></td>
</tr>
<tr align="center">
<td><img src="https://raw.githubusercontent.com/Tetrax-10/jellyfin-cover-art-generator/main/assets/Music.jpg" style="width: 400px;"></td>
<td><img src="https://raw.githubusercontent.com/Tetrax-10/jellyfin-cover-art-generator/main/assets/xxx.jpg" style="width: 400px;"></td>
</tr>
</table>

feat(others): add jellyfin-cover-art-generator

---

README.md
assets/DateCheck.sh

- Added DateCheck.sh for updateing Stale indicators in README.md
- Updated README.md
- Fixed ErsatzTV Github URL

Updated README and more

---

README.md
assets/clients/clients.yaml

Adds Jellyflix requested in #62

feat: add `Jellyflix`

---

README.md

Themerr-jellyfin supports tv shows since https://github.com/LizardByte/Themerr-jellyfin/pull/223

docs: update description of Themerr-jellyfin

---

README.md

add deprecation notice for jellyscrub

---

THEMES.md

Fix dead links in scyfin preview, plus add showcase for supported themes

Update THEMES.md to fix scyfin images

---

README.md
THEMES.md

**Added**
+ [jellyfin-plugin-media-cleaner](https://github.com/shemanaev/jellyfin-plugin-media-cleaner)
+ [jellyfin-plugin-onepace](https://github.com/jwueller/jellyfin-plugin-onepace)
+ [JellyRoller](https://github.com/LSchallot/JellyRoller)
+ [ytdlp2STRM](https://github.com/fe80Grau/ytdlp2STRM)
+ [Jellyman](https://github.com/Smiley-McSmiles/jellyman)
**Removed**
+ BlueBerry Theme (because it is archived now)
**Other**
+ Updated Outdated Indicators

Some Changes

---

README.md

feat: add `tubearchivist-jf-plugin`

---

README.md

feat: added `jellyfin-plugin-TelegramNotifier`

---

README.md

feat: added `JellySearch`

---

THEMES.md

feat: add new themes

---

assets/clients/clients.yaml

Changed JellyPlayer to Blink

---

README.md

Very useful for downloading subtitles from opensubtitles.com, even recursively.

Add OpenSubtitlesDownload to README.md

---

README.md

Closes #105 
(as the creator of this, it was a pleasant surprise to see it as a request already)

Add List-Sync to README.md

---

README.md

Includes `jelly-clipper`. 
Closes #125

feat: add `jelly-clipper`

---

assets/clients/clients.yaml

Add ` 🎵 ` to gelli to indicate music client

Add ` 🎵 ` to gelli

---

README.md

Adds **[jellyfin-plugin-collection-import](https://github.com/jellyfin-plugin-collection-import)** to the README.
Closes #135
(automatically generated)

(auto) Add `jellyfin-plugin-collection-import` to Awesome Jellyfin

---

README.md

chore: removed `FinTube`

---

README.md
assets/clients/clients.yaml

Adds **[app](https://github.com/app)** to the README.
Closes #130
(automatically generated)

(auto) Add `app` to Awesome Jellyfin

---

README.md

Remove `jellyfin-lyrics-plugin`

---

THEMES.md

feat: added ZestyTheme

---

.github/workflows/sorting-pull-check.yaml

This workflow checks if the README.md is correctly sorted and outputs a diff if not

ci: create `sorting-pull-check.yaml`

---

README.md

feat: add Posterizarr

---

README.md

feat: add `autopulse`

---

assets/clients/clients.yaml

feat: add `Fladder` client

---

README.md

Add jellyfin-plugin-cinemamode

---

README.md

closes #148 
closes #152 
closes #120

Add CineSync, media-upload-plugin and jellyfin-plugin-listenbrainz

---

README.md

Closes #189 
Closes #124 
Closes #121 
Closes #118

Batch insertion of Requests

---

README.md

feat: add `AudioBookRequest`

---

THEMES.md

fix: ZestyTheme link

---

assets/clients/clients.yaml

feat: added AfuseKt, AfuseKt TV and FluentFin

---

assets/clients/clients.yaml

feat: add VidHub client to AndroidTV

---

THEMES.md

feat: add `cappuccin` theme

---

README.md

chore: update description of `media-upload-plugin`

---

THEMES.md

feat: add finity theme

---

assets/clients/clients.yaml

fix: split AfuseKt and AfuseKtV

---

assets/clients/clients.yaml

closes #275 #273 #272 #230 #231 #232 #233 #229 #221

feat: add some clients
